import type { ipc } from '@x/shared';

// The RPC surface this server exposes over POST /rpc/{channel}. This is the
// strangler-fig migration frontier: channels move here from Electron main's
// in-process handlers group by group; anything not listed 404s (the full
// channel surface is not leaked to unauthenticated probing by name).
//
// turns:subscribe / turns:unsubscribe are deliberately absent — delta
// subscription needs connection identity, so it lives on the WebSocket
// (`{type:'subscribe', topic:'turn-deltas', turnId}`), not HTTP.
export const RPC_CHANNELS = [
  'sessions:list',
  'sessions:create',
  'sessions:get',
  'sessions:getTurn',
  'sessions:sendMessage',
  'sessions:respondToPermission',
  'sessions:respondToAskHuman',
  'sessions:stopTurn',
  'sessions:resumeTurn',
  'sessions:setTitle',
  'sessions:delete',
  'account:getRowboat',
  'workspace:getRoot',
  'workspace:exists',
  'workspace:stat',
  'workspace:readdir',
  'workspace:readFile',
  // Phase 1 (SEPARATION_PLAN.md): read-only queries. Connectors, code-mode,
  // and apps namespaces migrate in their own phases.
  'mcp:listTools',
  'runs:list',
  'runs:listByWorkDir',
  'sessions:listQueued',
  'models:list',
  'models:listForProvider',
  'models:getConfig',
  'llm:getDefaultModel',
  'rowboat:getConfig',
  'granola:getConfig',
  'knowledgeSources:getConfig',
  'onboarding:getStatus',
  'agent-schedule:getConfig',
  'agent-schedule:getState',
  'voice:getConfig',
  'live-note:get',
  'live-note:listNotes',
  'todo:get',
  'todo:getPlanner',
  'todo:getSessionConversation',
  'todo:getConversation',
  'todo:listArchived',
  'home:threads',
  'bg-task:get',
  'bg-task:list',
  'bg-task:listRunIds',
  'billing:getInfo',
  'credits:getState',
  'notifications:getSettings',
  'turnLimits:getSettings',
  'retention:getSettings',
  // Phase 2 (SEPARATION_PLAN.md): workspace & knowledge writes, todo/home/
  // deck state, settings setters. pickImage/exportCopy stay client-local
  // (native dialogs).
  'workspace:writeFile',
  'workspace:mkdir',
  'workspace:rename',
  'workspace:copy',
  'workspace:remove',
  'deck:generateOutline',
  'deck:generateSlide',
  'deck:editSlide',
  'knowledgeSources:upsert',
  'onboarding:markComplete',
  'knowledge:history',
  'knowledge:fileAtCommit',
  'knowledge:restore',
  'todo:acceptSuggestion',
  'todo:declineSuggestion',
  'todo:setPlanner',
  'todo:save',
  'todo:addItem',
  'todo:addSubItem',
  'todo:runItem',
  'todo:stopRun',
  'todo:startChat',
  'todo:chatReply',
  'todo:comment',
  'todo:clearCompleted',
  'todo:dismiss',
  'todo:teach',
  'todo:deleteArchived',
  'todo:restore',
  'home:markSeen',
  'home:setPinned',
  'home:snooze',
  'home:dismiss',
  'home:commandCenter',
  'notifications:setSettings',
  'turnLimits:setSettings',
  'retention:setSettings',
  'retention:consumeFirstRunNotice',
  // Phase 3a (SEPARATION_PLAN.md): connector data channels — verbatim lifts.
  // OAuth flow-starting channels (oauth:*, composio:*, chatgpt:signIn,
  // githubAuth:start, google-docs:pickViaManaged) relocate in Phase 3b; the
  // Slack desktop-import channels are client-machine edge capabilities and
  // stay in main permanently.
  'gmail:getImportant',
  'gmail:getEverythingElse',
  'gmail:triggerSync',
  'gmail:sendReply',
  'gmail:saveDraft',
  'gmail:deleteDraft',
  'gmail:getDrafts',
  'gmail:search',
  'gmail:getConnectionStatus',
  'gmail:getAccountEmail',
  'gmail:getAccountName',
  'gmail:setImportance',
  'gmail:setCategory',
  'gmail:archiveCategory',
  'gmail:getEmailInstructions',
  'gmail:setEmailInstructions',
  'gmail:getEmailLabels',
  'gmail:archiveThread',
  'gmail:trashThread',
  'gmail:markThreadRead',
  'gmail:downloadAttachment',
  'gmail:saveMessageHeight',
  'gmail:searchContacts',
  'chatgpt:getStatus',
  'channels:getConfig',
  'channels:setConfig',
  'channels:getStatus',
  'channels:whatsappLogout',
  'slack:getConfig',
  'slack:setConfig',
  'slack:cliStatus',
  'slack:knowledgeStatus',
  'slack:listWorkspaces',
  'slack:parseCurlAuth',
  'slack:listChannels',
  'slack:getRecentMessages',
  'google-docs:getStatus',
  'google-docs:import',
  'google-docs:refreshSnapshot',
  'google-docs:sync',
  'google-docs:getLink',
  'githubAuth:poll',
  'githubAuth:status',
  'githubAuth:signOut',
  'migration:check-composio-google',
  // Phase 3b (SEPARATION_PLAN.md): OAuth/connector flows — the loopback
  // server and orchestration live in core now; opening the browser is a
  // client capability delegated through the url-opener seam (RFC Q14 in DI
  // form; a WS capability request after the flip).
  'oauth:connect',
  'oauth:disconnect',
  'oauth:list-providers',
  'oauth:getState',
  'composio:is-configured',
  'composio:set-api-key',
  'composio:initiate-connection',
  'composio:get-connection-status',
  'composio:sync-connection',
  'composio:disconnect',
  'composio:list-connected',
  'composio:list-toolkits',
  'composio:execute-tool',
  'composio:search-tools',
  'chatgpt:signIn',
  'chatgpt:cancelSignIn',
  'chatgpt:signOut',
  'githubAuth:start',
  'google-docs:pickViaManaged',
] as const satisfies readonly ipc.InvokeChannels[];

export type RpcChannel = (typeof RPC_CHANNELS)[number];

export function isRpcChannel(channel: string): channel is RpcChannel {
  return (RPC_CHANNELS as readonly string[]).includes(channel);
}

// One handler per exposed channel. No Electron event argument — handlers are
// transport-agnostic; connection identity is a WS concern, never an RPC one.
export type RpcHandlers = {
  [K in RpcChannel]: (
    args: ipc.IPCChannels[K]['req'],
  ) => ipc.IPCChannels[K]['res'] | Promise<ipc.IPCChannels[K]['res']>;
};
