// AUTO-GENERATED by packages/core/scripts/gen-engine-manifest.mjs — do not edit by hand.
// Regenerate after bumping the @agentclientprotocol/*-acp adapter (engine) versions.
// Maps each agent + platform to the npm tarball + integrity of its native engine.

export const ENGINE_MANIFEST = {
    "claude": {
        "version": "0.3.257",
        "platforms": {
            "darwin-arm64": {
                "pkg": "@anthropic-ai/claude-agent-sdk-darwin-arm64",
                "pkgVersion": "0.3.257",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-darwin-arm64/-/claude-agent-sdk-darwin-arm64-0.3.257.tgz",
                "integrity": "sha512-ITjFPYB8riu9tbxbrWArokiZ/90w/NDrYbtEvyr3ScilVtu1iupkComxkhvbUxoyT4JRDpKsdw/ZOfwSl/pkpA=="
            },
            "darwin-x64": {
                "pkg": "@anthropic-ai/claude-agent-sdk-darwin-x64",
                "pkgVersion": "0.3.257",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-darwin-x64/-/claude-agent-sdk-darwin-x64-0.3.257.tgz",
                "integrity": "sha512-0s7QoLRnopbMvCqVpgCnvBWg4UNxPUybMZTknkn3HLBMvUjUdHs1QXb77c/yrT1WAPqDTw1Ju+H0esXwWa8/Kg=="
            },
            "linux-x64": {
                "pkg": "@anthropic-ai/claude-agent-sdk-linux-x64",
                "pkgVersion": "0.3.257",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-x64/-/claude-agent-sdk-linux-x64-0.3.257.tgz",
                "integrity": "sha512-0FRyIwV4jEJErdDDoYMC0v9lzuFNz5y0lK2340H5fP02eNXsP3U0htKW/bfRP8Ppei+xc4QUZgdCI6rVzkhXGg=="
            },
            "linux-arm64": {
                "pkg": "@anthropic-ai/claude-agent-sdk-linux-arm64",
                "pkgVersion": "0.3.257",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-arm64/-/claude-agent-sdk-linux-arm64-0.3.257.tgz",
                "integrity": "sha512-38tv1s1CaIE6CyEBmJpfKtvwPzrasxPiRT079BEs5aaiLPQ+pmSGF0+Lwy7ot9i6xqr7v5/91TVo5JXHI8Pkpg=="
            },
            "linux-x64-musl": {
                "pkg": "@anthropic-ai/claude-agent-sdk-linux-x64-musl",
                "pkgVersion": "0.3.257",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-x64-musl/-/claude-agent-sdk-linux-x64-musl-0.3.257.tgz",
                "integrity": "sha512-qSlgAUEpj2JAA+YqMD222iv2W3x8xBDSYwdoaOx20VbaJRjFq8feViI7kcr1C6wVN+ApX4Rxl7YX6gekiBkA2g=="
            },
            "linux-arm64-musl": {
                "pkg": "@anthropic-ai/claude-agent-sdk-linux-arm64-musl",
                "pkgVersion": "0.3.257",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-arm64-musl/-/claude-agent-sdk-linux-arm64-musl-0.3.257.tgz",
                "integrity": "sha512-t2WHfKjY4Jjgzfk0lbBUt6EVPQe+wXvXvRmYnK7ICfzZ1jS8CrpDajwBQErKFSMiUqGAutZy3vwDwGziW32cpw=="
            },
            "win32-x64": {
                "pkg": "@anthropic-ai/claude-agent-sdk-win32-x64",
                "pkgVersion": "0.3.257",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-win32-x64/-/claude-agent-sdk-win32-x64-0.3.257.tgz",
                "integrity": "sha512-NW0zMjHXFBdu2TcjT9Zo5o/1tJaDy6A7v4Gt/vLVJgaipV/RzAbyRGXZzH37hswyiKrSLGaSoYYP1vUfncbkUQ=="
            },
            "win32-arm64": {
                "pkg": "@anthropic-ai/claude-agent-sdk-win32-arm64",
                "pkgVersion": "0.3.257",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-win32-arm64/-/claude-agent-sdk-win32-arm64-0.3.257.tgz",
                "integrity": "sha512-7iEwy14lSqaAWvNR3KucBusQs5+hG6uoliYWZ2M2FyaCk5PHYymVf9mrRPtWhaYfNwum/YY13acYIIvnAbz0kA=="
            }
        }
    },
    "codex": {
        "version": "0.153.4",
        "platforms": {
            "darwin-arm64": {
                "pkg": "@openai/codex",
                "pkgVersion": "0.153.4-darwin-arm64",
                "tarball": "https://registry.npmjs.org/@openai/codex/-/codex-0.153.4-darwin-arm64.tgz",
                "integrity": "sha512-B1qhN3fa1ay0R0wGziXqgwSkB5icpYChNKHhtBHff/0UtSTC7z+l8aTtvMlGjH3E8HEvY3+njIJelM9CAAoVWg=="
            },
            "darwin-x64": {
                "pkg": "@openai/codex",
                "pkgVersion": "0.153.4-darwin-x64",
                "tarball": "https://registry.npmjs.org/@openai/codex/-/codex-0.153.4-darwin-x64.tgz",
                "integrity": "sha512-vnSbbPzfoDZmmyzsxswsDDXQ06IVFBzkQU7/hroB3ji93Ok2utcsq8Psfk2tjF5r9mEx8RWFJhzuTGHG26/NDA=="
            },
            "linux-x64": {
                "pkg": "@openai/codex",
                "pkgVersion": "0.153.4-linux-x64",
                "tarball": "https://registry.npmjs.org/@openai/codex/-/codex-0.153.4-linux-x64.tgz",
                "integrity": "sha512-x1EcwBlY3AObM1VTUHNM2AzAJQsyreGdagpF+qFiYi/Oa30VBktvvG0C6tLtCzqW6hjZNWkGZQWmeVk7MuJKWg=="
            },
            "linux-arm64": {
                "pkg": "@openai/codex",
                "pkgVersion": "0.153.4-linux-arm64",
                "tarball": "https://registry.npmjs.org/@openai/codex/-/codex-0.153.4-linux-arm64.tgz",
                "integrity": "sha512-QKdjYLYV4hXIuUQDP3P6F4NXuWFoKo9WUoV4nAREIx55kiUyi8UsYdsVobkeXir5n/maEQgYMCKLHVma4rNPiw=="
            },
            "win32-x64": {
                "pkg": "@openai/codex",
                "pkgVersion": "0.153.4-win32-x64",
                "tarball": "https://registry.npmjs.org/@openai/codex/-/codex-0.153.4-win32-x64.tgz",
                "integrity": "sha512-lMkB43kJZH0VFr+hoXc11qqR7QtQIbkr07ALgj4urKL1osNyUyuy1iXd3Vzz2iCYvBUCSw7I0l/W1cEPGx9euQ=="
            },
            "win32-arm64": {
                "pkg": "@openai/codex",
                "pkgVersion": "0.153.4-win32-arm64",
                "tarball": "https://registry.npmjs.org/@openai/codex/-/codex-0.153.4-win32-arm64.tgz",
                "integrity": "sha512-/FBh42976ltF1kxDoPQBg1Q6+hwChRU5/sm5dfeC8kFVQMvOCGoGeY5d8rRZGVJE8XojlXo74VQb0sHowcfgBw=="
            }
        }
    }
} as const;
