apiVersion: v1
kind: Service
metadata:
  name: litellm-proxy
  labels:
    app: litellm-proxy
spec:
  selector:
    app: litellm-proxy
  ports:
  - port: 4000
    targetPort: 4000
    name: http
  type: ClusterIP 