apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  REDIS_URL: "redis://redis:6379"
  MONGODB_CONNECTION_STRING: "mongodb://admin:password@mongodb:27017/rowboat?authSource=admin"
  AUTH0_DOMAIN: "dev-8yopv4xu0lclcsv3.us.auth0.com"
  AUTH0_AUDIENCE: "https://dev-8yopv4xu0lclcsv3.us.auth0.com/api/v2/"
  AUTH0_BASE_URL: "https://k3s.sjfisher.com"
  AUTH0_ISSUER_BASE_URL: "https://dev-8yopv4xu0lclcsv3.us.auth0.com"
  USE_AUTH: "false"
  USE_RAG: "true"
  AGENTS_API_URL: "http://rowboat-agents:3001"
  COPILOT_API_URL: "http://copilot:3002"
  USE_RAG_UPLOADS: "true"
  USE_RAG_SCRAPING: "true"
  USE_CHAT_WIDGET: "false"
  CHAT_WIDGET_HOST: "http://localhost:3006"
  MAX_QUERIES_PER_MINUTE: "60"
  MAX_PROJECTS_PER_USER: "10"
  VOICE_API_URL: ""
  PROVIDER_DEFAULT_MODEL: "groq/llama-3.3-70b-versatile"
  PROVIDER_COPILOT_MODEL: "gpt-4.1"
  PROVIDER_BASE_URL: "http://litellm-proxy:4000/v1"
  MAX_CALLS_PER_CHILD_AGENT: "10"
  ENABLE_TRACING: "false" 