packages:
  - apps/*
  - packages/*

allowBuilds:
  core-js: set this to true or false
  electron: set this to true or false
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
  fs-xattr: set this to true or false
  macos-alias: set this to true or false
  protobufjs: set this to true or false

catalog:
  vitest: 4.1.7

onlyBuiltDependencies:
  - core-js
  - electron
  - electron-winstaller
  - esbuild
  - better-sqlite3
  - fs-xattr
  - macos-alias
  - protobufjs
patchedDependencies:
  '@openai/codex@0.128.0': patches/@openai__codex@0.128.0.patch
