packages:
  - apps/*
  - packages/*

allowBuilds:
  baileys: true
  core-js: true
  electron: true
  electron-winstaller: true
  esbuild: true
  fs-xattr: true
  macos-alias: true
  node-pty: true
  protobufjs: true

overrides:
  vscode-jsonrpc: 8.2.0

catalog:
  vitest: 4.1.7

onlyBuiltDependencies:
  - baileys
  - core-js
  - electron
  - electron-winstaller
  - esbuild
  - fs-xattr
  - macos-alias
  - protobufjs
