#!/usr/bin/env node
// Applies the Baarali brand to a checkout, just before a build (option A,
// decided 01/10/2026). The repository keeps the upstream files as they are,
// so a weekly sync never conflicts on a brand line (UPSTREAM.md §2); the
// brand is written into the build's own copy, in CI or in a Docker stage.
//
//   node brand.mjs --check          says what it would change, writes nothing
//   node brand.mjs --yes            the desktop app: strings, names, icons, link to the instance
//   node brand.mjs --yes --only core   the instance image: what the agent says of itself
//
// Every exact edit must find its anchor exactly once: when the upstream
// changes one, the build fails here instead of shipping half a brand. The
// brand test (test/brand.test.ts) runs --check on every pull request.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
export const ROOT = path.resolve(here, '../../../../..');
const PKG = path.resolve(here, '..');

export const BRAND = {
  name: 'Baarali',
  apiUrl: 'https://app.baarali.com',
  site: 'https://baarali.com/',
  repo: 'benewende-dev/warell',
  contact: 'contact@baarali.com',
  bundleId: 'com.baarali.app',
  description: "L'assistant qui agit pour vous",
  publisher: 'OpenBaara',
};

// "Rowboat" alone, as the product's name. Not "Rowboat Labs" (the company,
// in tests and comments), nor the credit line below, nor identifiers like
// RowboatServer (\b stops at the next letter). Internal ids keep their
// lowercase `rowboat` (UPSTREAM.md §2 « Ce qu'on ne renomme jamais »).
const PRODUCT_NAME = /\bRowboat\b(?! Labs)(?! \(Apache)/g;

/** Where the upstream links its own company; ours instead. */
const LINKS = [
  ['https://github.com/rowboatlabs/rowboat', `https://github.com/${BRAND.repo}`],
  ['"rowboatlabs/rowboat"', `"${BRAND.repo}"`],
  ['https://www.rowboatlabs.com/terms-of-service', BRAND.site],
  ['https://www.rowboatlabs.com/privacy-policy', BRAND.site],
  ['https://www.rowboatlabs.com/', BRAND.site],
  ['contact@rowboatlabs.com', BRAND.contact],
  ['https://api.x.rowboatlabs.com', BRAND.apiUrl],
  ["homepage: 'https://rowboatlabs.com'", `homepage: '${BRAND.site}'`],
  ["maintainer: 'rowboatlabs'", `maintainer: '${BRAND.publisher}'`],
  ["'AI coworker with memory'", JSON.stringify(BRAND.description)],
];

/** The visible text of one source file, branded. */
export function brandText(text) {
  let out = text;
  for (const [from, to] of LINKS) out = out.split(from).join(to);
  // Apache-2.0 §4: say where it comes from; the company is not ours to name as the maker.
  out = out.split('Made by Rowboat Labs · Apache 2.0').join(`Made by ${BRAND.publisher} · Built on Rowboat (Apache 2.0)`);
  return out.replace(PRODUCT_NAME, BRAND.name);
}

const SOURCE_EXT = /\.(ts|tsx|html)$/;
const isTest = (file) => /\.test\.|\/__tests__\/|\/test\//.test(file);

function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name !== 'node_modules' && entry.name !== 'dist') walk(full, out);
    } else if (SOURCE_EXT.test(entry.name) && !isTest(full)) out.push(full);
  }
  return out;
}

/** The source trees whose strings are branded. */
export function sourceTrees(only) {
  const core = ['apps/x/packages/core/src'];
  if (only === 'core') return core;
  // forge.config.cjs: the installers' names and the macOS permission prompts.
  return [...core, 'apps/x/apps/main/src', 'apps/x/apps/main/forge.config.cjs', 'apps/x/apps/renderer/src', 'apps/x/apps/renderer/index.html'];
}

/** One exact replacement, which must match exactly once. */
function edit(file, from, to) {
  return { file, from, to };
}

// Without an Apple certificate, macOS reports a downloaded app whose
// signature broke at packaging as damaged, with no way past it; signed ad
// hoc, it is only unverified, and the person can allow it in the settings.
const ADHOC_SIGN = `        // Baarali (brand.mjs): ad hoc signature when there is no certificate.
        postPackage: async (_config, result) => {
            if (result.platform !== 'darwin' || !SKIP_CODE_SIGNING) return;
            const { execFileSync } = require('child_process');
            for (const dir of result.outputPaths) {
                for (const name of require('fs').readdirSync(dir).filter((n) => n.endsWith('.app'))) {
                    execFileSync('codesign', ['--force', '--deep', '--sign', '-', path.join(dir, name)], { stdio: 'inherit' });
                }
            }
        },
`;

// The cloud link (src/cloud-link.ts) and the few lines that start it.
const CLOUD_GLUE = `// Generated by apps/baarali/packages/desktop/scripts/brand.mjs: not in the repository.
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { app, dialog } from 'electron';
import { WorkDir } from '@x/core/dist/config/config.js';
import { API_URL } from '@x/core/dist/config/env.js';
import { connectRemoteServer, serverHostMode } from './server-host.js';
import { broadcastReload } from './ipc.js';
import { startCloudLink, type LinkProblem } from './baarali-cloud-link.js';

const MESSAGES: Record<'fr' | 'en', Record<LinkProblem, string>> = {
  fr: {
    instances_full: "L'accès anticipé est complet pour le moment. Vous êtes connecté : votre espace sera ouvert dès qu'une place se libère.",
    unavailable: "Votre espace Baarali ne répond pas pour le moment. Réessayez dans quelques minutes : déconnectez-vous puis reconnectez-vous.",
  },
  en: {
    instances_full: 'Early access is full for now. You are signed in: your space opens as soon as a seat frees up.',
    unavailable: 'Your Baarali space is not answering right now. Try again in a few minutes: sign out, then sign in again.',
  },
};

export function startBaaraliCloud(): void {
  const oauthFile = path.join(WorkDir, 'config', 'oauth.json');
  startCloudLink({
    apiUrl: API_URL,
    oauthFile,
    mode: serverHostMode,
    connect: connectRemoteServer,
    reload: () => setTimeout(() => broadcastReload(), 400),
    notify: (problem) => {
      const lang = app.getLocale().startsWith('fr') ? 'fr' : 'en';
      void dialog.showMessageBox({ type: 'info', message: 'Baarali', detail: MESSAGES[lang][problem] });
    },
    deviceName: () => os.hostname().replace(/\\.local$/, ''),
    readFile: (file) => fsp.readFile(file, 'utf8'),
    watch: (file, onChange) => {
      // Polling: the upstream rewrites the file whole, which fs.watch loses on some systems.
      fs.watchFile(file, { interval: 1000 }, onChange);
      return () => fs.unwatchFile(file, onChange);
    },
    fetch: globalThis.fetch,
    now: Date.now,
    sleep: (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
    log: (message) => console.log(message),
  });
}
`;

export function desktopPlan() {
  const main = 'apps/x/apps/main';
  return {
    edits: [
      edit(`${main}/forge.config.cjs`, "appBundleId: 'com.rowboat.app',", `appBundleId: '${BRAND.bundleId}',`),
      edit(`${main}/forge.config.cjs`, "authors: 'rowboatlabs',", `authors: '${BRAND.publisher}',`),
      edit(
        `${main}/forge.config.cjs`,
        "iconUrl: 'https://raw.githubusercontent.com/rowboatlabs/rowboat/main/apps/x/apps/main/icons/icon.ico',",
        `iconUrl: 'https://raw.githubusercontent.com/${BRAND.repo}/main/apps/baarali/packages/desktop/assets/icon.ico',`,
      ),
      edit(`${main}/forge.config.cjs`, "owner: 'rowboatlabs',\n                    name: 'rowboat'", `owner: '${BRAND.repo.split('/')[0]}',\n                    name: '${BRAND.repo.split('/')[1]}'`),
      edit(`${main}/forge.config.cjs`, '    hooks: {\n', `    hooks: {\n${ADHOC_SIGN}`),
      edit(
        `${main}/src/main.ts`,
        "import { initUpdater } from \"./updater.js\";",
        "import { initUpdater } from \"./updater.js\";\nimport { startBaaraliCloud } from \"./baarali-cloud.js\";",
      ),
      edit(
        `${main}/src/main.ts`,
        "  startServerHost().catch((error) => {\n    console.error('[server-host] failed to start rowboat-server:', error);\n  });",
        "  startServerHost().catch((error) => {\n    console.error('[server-host] failed to start rowboat-server:', error);\n  });\n  startBaaraliCloud();",
      ),
      // The brand's colours, loaded after App.css (src/baarali-theme.css).
      edit('apps/x/apps/renderer/src/main.tsx', "import App from './App.tsx'\n", "import App from './App.tsx'\nimport './baarali-theme.css'\n"),
    ],
    copies: [
      ['assets/icon.icns', `${main}/icons/icon.icns`],
      ['assets/icon.ico', `${main}/icons/icon.ico`],
      ['assets/icon.png', `${main}/icons/icon.png`],
      ['assets/install-loading.gif', `${main}/icons/install-loading.gif`],
      ['assets/logo-only.png', 'apps/x/apps/renderer/public/logo-only.png'],
      ['src/cloud-link.ts', `${main}/src/baarali-cloud-link.ts`],
      ['src/baarali-theme.css', 'apps/x/apps/renderer/src/baarali-theme.css'],
    ],
    writes: [[`${main}/src/baarali-cloud.ts`, CLOUD_GLUE]],
    packageJson: {
      file: `${main}/package.json`,
      set: { productName: BRAND.name, description: BRAND.description },
    },
  };
}

/**
 * Computes every change; throws on a missing anchor. Writes only with `write`.
 * @param {{ root?: string, only?: string, write?: boolean }} options
 * @returns {string[]}
 */
export function apply({ root = ROOT, only, write = false }) {
  const changes = [];
  // A Windows checkout ends lines with CRLF (git's autocrlf): the anchors
  // are written with LF, so the build copy is read, and written, in LF.
  const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8').replace(/\r\n/g, '\n');
  const pending = new Map();
  const current = (rel) => (pending.has(rel) ? pending.get(rel) : read(rel));

  if (only !== 'core') {
    const plan = desktopPlan();
    for (const e of plan.edits) {
      const text = current(e.file);
      const count = text.split(e.from).length - 1;
      if (count !== 1) throw new Error(`brand: ${e.file}: expected the anchor once, found it ${count} times:\n${e.from}`);
      pending.set(e.file, text.replace(e.from, () => e.to));
    }
    const pj = JSON.parse(current(plan.packageJson.file));
    pending.set(plan.packageJson.file, JSON.stringify({ ...pj, ...plan.packageJson.set }, null, 4) + '\n');
    for (const [from, to] of plan.copies) {
      if (!fs.existsSync(path.join(PKG, from))) throw new Error(`brand: missing ${from}`);
      changes.push(`copy ${from} → ${to}`);
      if (write) fs.copyFileSync(path.join(PKG, from), path.join(root, to));
    }
    for (const [to, text] of plan.writes) {
      changes.push(`write ${to}`);
      if (write) fs.writeFileSync(path.join(root, to), text);
    }
  }

  for (const tree of sourceTrees(only)) {
    const abs = path.join(root, tree);
    const files = fs.statSync(abs).isDirectory() ? walk(abs) : [abs];
    for (const file of files) {
      const rel = path.relative(root, file);
      const text = current(rel);
      const branded = brandText(text);
      if (branded !== text) pending.set(rel, branded);
    }
  }

  for (const [rel, text] of pending) {
    if (text === read(rel)) continue;
    changes.push(`edit ${rel}`);
    if (write) fs.writeFileSync(path.join(root, rel), text);
  }
  return changes;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const args = process.argv.slice(2);
  const only = args.includes('--only') ? args[args.indexOf('--only') + 1] : undefined;
  const check = args.includes('--check');
  // It rewrites tracked files: never by accident in a working copy.
  if (!check && !args.includes('--yes')) {
    console.error('brand.mjs rewrites tracked files. Run it in CI or a build stage with --yes, or use --check.');
    process.exit(2);
  }
  const changes = apply({ only, write: !check });
  console.log(`${check ? 'would apply' : 'applied'} ${changes.length} change(s)`);
}
